featureset:
  name: "smiles_tokenizer"

featurizer:
  name: "smiles_tokenizer"
  pretrained_name: "seyonec/ChemBERTa-zinc-base-v1"
  max_length: 256
  padding: "max_length"
  truncation: true
  add_special_tokens: true
  use_fast: true
  local_files_only: false
